const express = require("express")
const router = express.Router()

// Importar todas las rutas
const usuarioRoutes = require("./usuario.routes")
const personaRoutes = require("./persona.routes")
const lineaInvestigacionRoutes = require("./lineaInvestigacion.routes")
const publicacionRoutes = require("./publicacion.routes")
const proyectoRoutes = require("./proyecto.routes")
const lineaExtensionRoutes = require("./lineaExtension.routes")
const novedadRoutes = require("./novedad.routes")
const extensionRoutes = require("./extension.routes")
const investigacionRoutes = require("./investigacion.routes")
const objetivoRoutes = require("./objetivo.routes")
const contenidoPresentacionRoutes = require("./contenidoPresentacion.routes")
const tarjetaFlotanteRoutes = require("./tarjetaFlotante.routes")
const contenidoHomeRoutes = require("./contenidoHome.routes")
const contenidoNovedadesRoutes = require("./contenidoNovedades.routes")
const contenidoPublicacionesRoutes = require("./contenidoPublicaciones.routes")
const contenidoExtensionRoutes = require("./contenidoExtension.routes")
const contenidoEquipoRoutes = require("./contenidoEquipo.routes")
const contenidoGaleriaRoutes = require("./contenidoGaleria.routes")

// Configurar rutas
router.use("/usuarios", usuarioRoutes)
router.use("/personas", personaRoutes)
router.use("/lineas-investigacion", lineaInvestigacionRoutes)
router.use("/publicaciones", publicacionRoutes)
router.use("/proyectos", proyectoRoutes)
router.use("/lineas-extension", lineaExtensionRoutes)
router.use("/novedades", novedadRoutes)
router.use("/extensiones", extensionRoutes)
router.use("/investigaciones", investigacionRoutes)
router.use("/objetivos", objetivoRoutes)
router.use("/contenido-presentacion", contenidoPresentacionRoutes)
router.use("/tarjetas-flotantes", tarjetaFlotanteRoutes)
router.use("/contenido-home", contenidoHomeRoutes)
router.use("/contenido-novedades", contenidoNovedadesRoutes)
router.use("/contenido-publicaciones", contenidoPublicacionesRoutes)
router.use("/contenido-extension", contenidoExtensionRoutes)
router.use("/contenido-equipo", contenidoEquipoRoutes)
router.use("/contenido-galeria", contenidoGaleriaRoutes)

module.exports = router
